#!/usr/bin/python
# TODO: rename this script appropriately
import rosbag
import sys
import datetime
import argparse
import exceptions
import struct
import comma
import numpy
from signal import signal, SIGPIPE, SIG_DFL
try:
    import rospy_message_converter
except ImportError:
    msg = """
cannot import rospy_message_converter module; usually you can install it as
    sudo apt-get install ros-kinetic-rospy-message-converter
(use your ROS distro name in place of kinetic). If the module is not available
in your package manager, build and install the module manually.
"""
    raise ImportError(msg)

help_description='extract global position data from ROS bag files'
help_examples="""
examples
    gps-bag-to-csv --file "input.bag"
    gps-bag-to-csv --file="input.bag" --topic "/mavros/global_position/raw/fix" --binary | csv-from-bin t,3d | head

hints
    get list of topic inside a bag:
        rostopic list -b <bag> 
    get info about a topic:
        rostopic echo <topic> -b <file> | less -S
        rostopic echo /mavros/global_position/global -b input.bag | head -n 32
"""

def remove_options( parser, options ):
    """argparse does not provide a standard way to remove or override options
this function handles it manually
"""
    for option in options:
        for action in parser._actions:
            for option_string in vars(action)['option_strings']:
                if option_string == option:
                    parser._handle_conflict_resolve( None, [(option, action)] )
                    break

def convert_ros_message_to_csv_record( message ):
    """
    Takes a ROS message and returns a comma.csv.struct (Python type) representing this message
    and a lambda function converting the message into an instance of the new comma.csv.struct
"""
    from rospy_message_converter import message_converter as mc

    message_fields = mc._get_message_fields(message)
    fields = []
    types = []
    ctors = []
    # see Python programming FAQ why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result
    # for the explanation of all the lambda signatures (and some function signatures in case of time)
    for field_name, field_type in message_fields:
        fields.append( field_name )
        if field_type in mc.ros_binary_types:
            ctor = lambda msg, field_name=field_name, field_type=field_type: mc._convert_to_ros_binary( field_type, getattr( msg, field_name ) )
            element_t = "S%d" % len( ctor( message ) )
        elif field_type in mc.ros_primitive_types:
            ctor = lambda msg, field_name=field_name: getattr( msg, field_name )
            element_t = field_type == 'string' and "S%d" % len( ctor( message ) ) or field_type
        elif field_type == 'time':
            def ctor( msg, field_name=field_name ):
                ts = getattr( msg, field_name )
                return numpy.datetime64( datetime.datetime.fromtimestamp( ts.secs + 1.0e-9 * ts.nsecs ) )
            element_t = 'datetime64[us]'
        elif field_type == 'duration':
            def ctor( msg, field_name=field_name ):
                ts = getattr( msg, field_name )
                return numpy.timedelta64( ts.secs, 's' ) + numpy.timedelta64( ts.nsecs, 'ns' )
            element_t = 'timedelta64[us]'
        elif mc._is_field_type_an_array(field_type):
            ctor = lambda msg, field_name=field_name: getattr( msg, field_name )
            m = mc.list_brackets.search( field_type )
            element_t = ( field_type[:m.start()], ( int(m.group()[1:-1]), ) )
        else:
            element_t, element_ctor = convert_ros_message_to_csv_record( getattr( message, field_name ) )
            ctor = lambda msg, field_name=field_name, element_ctor=element_ctor: element_ctor( getattr( msg, field_name ) )
        ctors.append( ctor )
        types.append( element_t )

    new_t = comma.csv.struct( ','.join( fields ), *types )
    return ( new_t, lambda msg, new_t=new_t: numpy.array( [ tuple( [ c(msg) for c in ctors ] ) ], dtype = new_t ) )

def main():
    parser = argparse.ArgumentParser( description=help_description, epilog=help_examples, formatter_class=argparse.RawDescriptionHelpFormatter, conflict_handler='resolve' )
    parser.add_argument( '--file', help='input bag file' )
    parser.add_argument( '--topic', help='topic in the bag file to be extracted', default='/mavros/global_position/global' )
    parser.add_argument( '--output-fields', help='print output fields and exit', action='store_true' )
    parser.add_argument( '--output-format', help='print output format for binary and exit', action='store_true' )
    comma.csv.add_options( parser )
    # override; normally --binary is used to describe input format and therefore, takes an argument; '--fields' makes sense only for input streams
    remove_options( parser, [ '-b', '--binary', '-f', '--fields' ] )
    parser.add_argument( '-b', '--binary', help='use binary output', action='store_true' )
# TODO: support '--fields' to select a sub-set of the fields to parse (optional; good to have)
    args = parser.parse_args()

    if args.file is None:
        raise exceptions.RuntimeError( "Input bag not specified" )
    try:
        with open( args.file ) as f:
            pass
    except IOError as e:
        raise exceptions.RuntimeError( "Unable to open file '%s' for reading" % args.file )

    signal(SIGPIPE, SIG_DFL) # do no want the IOError message trace

    with rosbag.Bag( args.file ) as bag:
        generator = bag.read_messages( topics=[ args.topic ] )
        topic, msg, t = generator.next()
        record_t, record_ctor = convert_ros_message_to_csv_record( msg )
        if args.output_fields:
            print ','.join( record_t.fields )
            sys.exit(0)
        if args.output_format:
            print comma.csv.format.from_numpy( record_t.format )
            sys.exit(0)
        ostream = comma.csv.stream( record_t, flush=args.flush, delimiter=args.delimiter, binary=args.binary )
        record = record_ctor( msg )
        ostream.write( record )
        for topic, msg, t in generator:
            record = record_ctor( msg )
            ostream.write( record )
    sys.exit(0)

if __name__ == '__main__':
    main()
