#!/bin/bash

scriptname=$( basename $0 )

source $( type -p comma-application-util ) || { echo "$scriptname: cannot source comma-application-util" >&2; exit 1; }

function usage()
{
cat <<EOF

publish data from vantage weather station

usage: $scriptname <robot-config>

EOF
    exit
}

(( $# == 1 )) || usage
[[ $1 == "-h" || $1 == "--help" ]] && usage

config_file_path=$1

function load_config()
{
    local file path
    IFS=: read file path <<< "$1"
    cat "$file" | name-value-get "$path"
}

comma_path_value_to_var --prefix=config < <( load_config $config_file_path )

vantage-to-csv --config $config_file_path/station | io-publish tcp:$config_port
