snark: pipeline Class Reference
pipeline Class Reference
base class for video processing, capture images in a serarate thread, apply filters, serialize to stdout
#include <pipeline.h>
Public Member Functions
pipeline (cv_mat::serialization &output, const std::string &filters, tbb::bursty_reader< pair > &reader)
void run ()
run the pipeline
Protected Member Functions
void setup_pipeline_ (const std::string &filters)
void write_ (pair p)
write frame to std out
Detailed Description
base class for video processing, capture images in a serarate thread, apply filters, serialize to stdout
Constructor & Destructor Documentation
pipeline (cv_mat::serialization & output, const std::string & filters, tbb::bursty_reader< pair > & reader)
constructor
Parameters
fields csv output fields
format csv output format
filters string describing the filters
size max buffer size
mode output mode
References pipeline::setup_pipeline_().
Member Function Documentation
void setup_pipeline_ (const std::string & filters) protected
setup the pipeline
Parameters
filters name-value string describing the filters
References filters::make(), and pipeline::write_().
Referenced by pipeline::pipeline().
The documentation for this class was generated from the following files:
pipeline.h
pipeline.cpp