#!/bin/bash

source $( type -p comma-application-util ) || { echo "cannot source 'comma-application-util'" >&2; exit 1; }

output_dir=output
[[ -d $output_dir ]] || mkdir $output_dir

# first line is args, second line is the fields and can be empty
read args
read fields
[[ $fields ]] || fields=$( points-calc $args --input-fields )
output_fields=$( points-calc $args --output-fields )
[[ -n $output_fields ]] || output_fields=$fields

echo "         args: $args" >&2
echo " input fields: $fields" >&2
echo "output fields: $output_fields" >&2

points-calc $args --fields="$fields" | tee $output_dir/raw \
    | csv-shuffle --fields="$fields,$output_fields" --output="$output_fields" \
    | cat -n | sed 's#^ *#output[#;s#\t#]="#;s#$#"#'

comma_status_ok || { echo "test failed" >&2; exit 1; }
