#!/bin/bash

source $( type -p comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }

inputs=$( cat )

echo "$inputs" |
    gawk '{ print "inputs[" NR-1 "]=\"" $0 "\""  }'

# result of filter
echo "$inputs" |
    csv-to-bin 4d | 
    cv-cat --input "no-header;rows=2;cols=1;type=2d" "accumulated=average" | 
    csv-from-bin "4d" --precision 6 |
    gawk '{ print "filters[" NR-1 "]=\"" $0 "\""  }'

# Applied filters
echo "$inputs" |
    csv-to-bin 4d | 
    cv-cat --input "no-header;rows=2;cols=1;type=2d" "divide=accumulated:average" | 
    csv-from-bin "4d" --precision 6 |
    gawk '{ print "image[" NR-1 "]=\"" $0 "\""  }'
