#!/bin/bash

source $( type -p comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }

read cv_depth

cv_depth=${cv_depth:-f} # Default to type f

inputs=$( cat )

echo "$inputs" |
    gawk '{ print "inputs[" NR-1 "]=\"" $0 "\""  }'

# result of filter
echo "$inputs" |
    csv-to-bin 4$cv_depth | 
    cv-cat --input "no-header;rows=2;cols=1;type=2$cv_depth" --output "no-header=0" | 
    cv-cat "accumulated=average" | 
    csv-from-bin "t,3ui,4$cv_depth" --precision 6 |
    gawk '{ print "filters[" NR-1 "]=\"" $0 "\""  }'

# Applied filters
echo "$inputs" |
    csv-to-bin 4$cv_depth | 
    cv-cat --input "no-header;rows=2;cols=1;type=2$cv_depth" --output "no-header=0" | 
    cv-cat "divide=accumulated:average" | 
    csv-from-bin "t,3ui,4$cv_depth" --precision 6 |
    gawk '{ print "image[" NR-1 "]=\"" $0 "\""  }'
