#!/bin/bash

config=config.json
prefix=ur5
publisher_port=$( name-value-get --from json $prefix/publisher/data/port < $config )
timeout=0.1
angle_tolerance=0.0001
status_sample=status_sample_stationary.bin

nc -d -z localhost $publisher_port && { echo "$( readlink -f `basename $0` ): required port $publisher_port is already in use, try changing publisher port in config.json" >&2; exit 1; }
ur-arm wait --target=1,2,3,4,5,6 --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
status=$?
echo "waypoint/no_publisher/status=$status"

while :; do cat $status_sample; done | io-publish -s $( ur-arm-status --packet-size ) tcp:$publisher_port 2>/dev/null &
pid=$!
ur-arm wait --target=1,2,3,4,5,6 --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
status=$?
echo "waypoint/timed_out/status=$status"
kill $pid

while :; do cat $status_sample; done | io-publish -s $( ur-arm-status --packet-size ) tcp:$publisher_port 2>/dev/null &
pid=$!
angles=$( cat $status_sample | ur-arm-status --fields=arm/angles )
ur-arm wait --target=$angles --config=$config --prefix=$prefix --timeout=$timeout --tolerance=$angle_tolerance
status=$?
echo "waypoint/success/status=$status"
kill $pid
