#!/bin/bash

source $( type -p comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }
source $( type -p comma-application-util ) || { echo "$0: failed to source comma-application-util" >&2 ; exit 1 ; }

inputs=$( cat )

cv_depth=ub
echo "$inputs" |
    csv-to-bin 6$cv_depth | 
    cv-cat --input "no-header;rows=2;cols=3;type=$cv_depth" --output "no-header=0" | 
    cv-calc count | csv-from-bin "t,3ui,ui" --precision 5 |
    gawk '{ print "image[" NR-1 "]=\"" $0 "\""  }'
comma_status_ok
code=$?
echo "status=$code"
