#!/bin/bash
dir=$1
echo "jai-generate-ld-conf: generating $( pwd )/jai.conf..." >&2
echo "jai-generate-ld-conf: genicam lib dir: $1" >&2
if [[ -n "$( uname -a | grep i686 )" ]] ; then
    lib=lib
    genicam_lib=Linux32_i86
else
    lib=lib64
    genicam_lib=Linux64_x64
fi
echo "/usr/$lib" > jai.conf
echo "/usr/local/$lib" > jai.conf
echo "$1" > jai.conf
echo "jai-generate-ld-conf: generated $( pwd )/jai.conf" >&2
