#!/bin/bash

function wait_for_port
{
    local port=$1
    local -i count=0
    local listen_state=$( io-ls --enum-state | grep ,LISTEN$ | cut -d, -f1 )
    while ! io-ls --fields local/port,state | grep $port,$listen_state &>/dev/null; do
        sleep 0.1
        if (( ++count > 100 )); then { echo "$scriptname: timed out waiting for port $port"; return 1; }; fi
    done
    echo "port $port is ready" >&2
}

function kill_if_exists
{
    local pid=$1
    local what=$2
    if kill -0 $pid &>/dev/null; then
        echo "killing $what (pid=$pid): $( date +%T.%N )" >&2
        kill $pid
        wait $pid
    fi
}

function bye
{
    kill_if_exists $feedback_pid feedback
    exit
}

trap bye INT HUP TERM EXIT

scriptname=$( readlink -f $0 )
source $( type -p comma-application-util ) || { echo "$scriptname: failed to source comma-application-util" >&2; exit 1; }
source $( type -p comma-process-util ) || { echo "$scriptname: failed to source comma-process-util" >&2; exit 1; }

mkdir -p output

feedback_fields=t,x,y,yaw
feedback_binary=t,d,d,d

fields=x,y,heading_offset
binary=d,d,d

output_format=$binary,$feedback_binary,$( control-error --output-format )
output_fields=$( csv-fields prefix --path target <<< $fields ),$( csv-fields prefix --path feedback <<< $feedback_fields ),$( control-error --output-fields )

dt=$( head -qn1 input data/feedback.csv | cut -d, -f1 | paste -sd, | csv-eval --fields a,b --format 2t "dt = (a-b)/timedelta64(1,'s')" | cut -d, -f3 )

feedback_port=$(( 1024 + $RANDOM ))
feedback_pid=
cat data/feedback.csv \
    | csv-play \
    | csv-to-bin $feedback_binary --flush \
    | socat -u - tcp-listen:$feedback_port & feedback_pid=$!

wait_for_port $feedback_port

sleep $dt

{
    cat input
    sleep 10
} \
    | csv-play \
    | csv-shuffle --fields t,x,y,heading --output-fields x,y,heading \
    | csv-to-bin $binary --flush \
    | control-error --fields=$fields  --binary=$binary \
        "tcp:localhost:$feedback_port;fields=$feedback_fields;binary=$feedback_binary" \
        --mode=fixed --proximity=5 --frequency=20 --past-endpoint --verbose \
    | csv-from-bin $output_format --flush \
    | csv-eval --fields $output_fields --format $output_format \
        "time_diff=( feedback_t - datetime64('2015-01-01T00:00:00.000000') )/timedelta64(1,'s')" --full-xpath --flush \
    | tee output/output.csv \
    | name-value-from-csv $output_fields,time_diff --line-number --prefix output \
    | csv-quote --unquote --fields ,x --delimiter =

cat output/output.csv \
    | csv-paste - line-number \
    | csv-select --fields $output_fields "reached;equals=1" \
    | rev | cut -d, -f1 | rev \
    | name-value-from-csv index --line-number --prefix reached \
    | csv-quote --unquote --fields ,x --delimiter =

