#!/usr/bin/python
import sys
import cv2 as cv
import numpy as np
import argparse
import json
from snark.imaging import cv_image
from comma.io import windows_binary

description = """

apply watershed algorithm to image stream

pixel labels will be output as single-channel 32-bit integer image (type CV_32SC1)
of the same size as the original

see cv-cat --help --verbose for input and output format details

usage
    read images from image stream; see cv-cat --help --verbose for image format details
        cat images.bin | image-watershed [<options>] > labels.bin
       
    read image from file
        cv-cat --file image.jpg | image-watershed [<options>] | cv-cat --output no-header > labels.bin

    read image from file and save results in new file
        cv-cat --file image.jpg | image-watershed [<options>] | cv-cat --output no-header "convert-to=ub;encode=jpg" > results.jpg

"""

parser = argparse.ArgumentParser( description = description )
parser.add_argument( '--view', action="store_true", help = 'view result' )
parser.add_argument( '--config', action="store", help = 'configuration file name' )
parser.add_argument( '--default-config', action="store_true", help = 'output default config and exit' )
args = parser.parse_args()

# set defaults
default_config = dict()
default_config['threshold'] = dict()
default_config['threshold']['min'] = 200
default_config['threshold']['max'] = 255
default_config['blur'] = dict()
default_config['blur']['radius'] = 5
default_config['blur']['iterations'] = 2
default_config['dilation'] = dict()
default_config['dilation']['iterations'] = 3

if( args.default_config ):
    print json.dumps( default_config )
    exit(0)

view_resize_factor = 0.25

# override defaults in config
config = default_config
if args.config:
    with open( args.config ) as config_file:
        loaded_config = json.load( config_file )
        config.update( loaded_config )

for i in cv_image.iterator( sys.stdin ):
    header = i.header
    header['type'] = cv.CV_32SC1
    watershed = np.zeros( ( header['rows'], header['cols'], 1 ), np.int32 )
    ret, thresholded = cv.threshold( i.data, float( config['threshold']['min'] ), float( config['threshold']['max'] ), cv.THRESH_BINARY )

    kernel = np.ones( ( float( config['blur']['radius'] ), float( config['blur']['radius'] ) ), np.uint8 )
    blurred = cv.morphologyEx( thresholded, cv.MORPH_OPEN,kernel, iterations = int( config['blur']['iterations'] ) )

    dilated = cv.dilate( blurred, kernel, iterations = int( config['dilation']['iterations'] ) )

    contours, hierarchy = cv.findContours( dilated, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE )

    for j in range( len( contours ) ):
        for k in range( len( contours[j] ) ):
            u = contours[j][k][0][0]
            v = contours[j][k][0][1]
            watershed[v][u] = j

    w = cv_image.image( header, watershed )
    if args.view :
        resized = cv.resize( w.data, None, fx=view_resize_factor, fy=view_resize_factor, interpolation = cv.INTER_NEAREST )
        cv.imshow( 'watershed', resized )
        cv.waitKey(10000)
    cv_image.write( w )
