#!/usr/bin/python

# This file is part of comma, a generic and flexible library
# Copyright (c) 2011 The University of Sydney
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University of Sydney nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
# GRANTED BY THIS LICENSE.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
# HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys
import cv2
import numpy as np
from optparse import OptionParser
from snark.imaging import cv_image
from comma.io import windows_binary


if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("--binary", dest="binary", action="store_true", default=False, help="binary output", metavar="BINARY")
    (options, args) = parser.parse_args()

    output = np.zeros(1, dtype='uint64,uint32,uint32,uint32,float64')

    for i in cv_image.iterator(sys.stdin):
        intensity = np.mean(i.data)

        if options.binary:
            output[0] = (i.header['time'].astype(np.uint64), i.header['rows'], i.header['cols'], i.header['type'], intensity)
            output.tofile(sys.stdout)
            sys.stdout.flush()
        else:
            print >> sys.stdout, "{},{},{},{},{}".format(i.header['time'].item(), i.header['rows'], i.header['cols'], i.header['type'], intensity)

        # cv2.imshow('test',i.data)
        # cv2.waitKey(1)

