#!/bin/bash

function clean
{
    pkill -P $$
    return 0
}
function bye { clean; exit 1; }
trap bye INT TERM HUP
trap clean EXIT

fields="speed,error/cross_track,error/heading"
read -d '' input <<END
10.0,0,0.01
11.0,0,-0.01
12.0,0.01,0
13.0,-0.01,0
14.0,0.01,0.01
15.0,-0.01,-0.01
16.0,0.01,-0.1
17.0,-0.01,0.1
END
output=( $( echo -e "$input" | control-command --fields=$fields --cross-track-pid=1.11111,0,0 --heading-pid=0.12345,0,0 --steering=skid ) )

function echo_skid_result
{
    local lhs=$1
    local result=$2
    local speed cross_track_error heading_error turn_rate
    IFS=, read speed cross_track_error heading_error turn_rate <<< $result
    echo "$lhs/speed=$speed"
    echo "$lhs/cross_track_error=$cross_track_error"
    echo "$lhs/heading_error=$heading_error"
    echo "$lhs/turn_rate=$turn_rate"
}

for(( i=0; i < ${#output[@]}; i++ )); do echo_skid_result "skid/output[$i]" ${output[i]}; done

clean
