#!/bin/bash

source $( type -p comma-application-util )

comma_path_value_to_var

cmd="view-points $files $args"

if [[ $input ]]; then
cat >&2 <<EOF
running:
    eval $input | eval $cmd &
EOF
    eval $input | eval $cmd &
else
cat >&2 <<EOF
running:
    eval $cmd
EOF
    eval $cmd &
fi
eval_pid=$!

[[ $instruction ]] && dialog_test="$instruction\n\n"
dialog_test+="Do you see $expected?"

zenity --question --text="$dialog_test"
result=$?

# zenity causes upstart to start an instance of dbus-launch, but this instance
# has the process gid of the comma-timeout-group used to launch all the tests.
# Which means that comma_execute_and_wait waits for it, and it takes a while to
# go away, so we'll kill it explicitly.
dbus_launch_pid=$( ps -o pid,comm | grep dbus-launch | cut -f1 -d' ' )
[[ $dbus_launch_pid ]] && kill $dbus_launch_pid

cat >&2 <<EOF
dialog_test: $dialog_test
result: $result
EOF

# view-points is the child of eval
kill $( pgrep -P $eval_pid )
wait $eval_pid
exit $result
