#!/bin/bash

source $( type -p comma-name-value-util )

# Strip leading and trailing white-space, comments and blank lines
test_input=$( sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | sed -n '/^[[:alnum:]]/p' )
comma_path_value_to_var < <( grep "=" <<< "$test_input" )

input=$( readlink -e $input )

output_dir=output

[[ -d $output_dir ]] || mkdir $output_dir
cd $output_dir

mat-convert $args $options < $input \
    | if [[ $options =~ --binary ]]; then csv-from-bin $( mat-convert $args $options --output-format < $input ); else cat; fi \
    | if [[ $options =~ (--to csv|--list|--output-format) ]]; then
          name-value-from-csv -f line -d : -n -p output
      else
          name-value-convert --no-brackets
      fi
