#!/bin/bash
dir=$1
echo "basler-generate-ld-conf: generating $( pwd )/basler.conf..." >&2
echo "basler-generate-ld-conf: PYLON_ROOT=$1" >&2
if [[ "$( uname -a | grep i686 )" != "" ]] ; then
    lib=lib
    genicam_lib=Linux32_i86
else
    lib=lib64
    genicam_lib=Linux64_x64
fi
echo "$dir/$lib" > basler.conf
echo "$dir/$lib/pylon/tl" >> basler.conf
echo "$dir/genicam/bin/$genicam_lib" >> basler.conf
echo "$dir/genicam/bin/$genicam_lib/GenApi/Generic" >> basler.conf
#echo "basler-generate-ld-conf: generated $(pwd)/basler.conf:" >&2
#echo "basler-generate-ld-conf: generated basler.conf; after make install, please run: sudo ldconfig" >&2
#cat basler.conf >&2
echo "basler-generate-ld-conf: generated $( pwd )/basler.conf" >&2
