#!/bin/bash

# This file is part of snark, a generic and flexible library for robotics research
# Copyright (c) 2016 The University of Sydney
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University of Sydney nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
# GRANTED BY THIS LICENSE.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
# HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

scriptname=$( basename $0 )

source $( type -p comma-application-util ) || { echo "$scriptname: cannot source comma-application-util" >&2; exit 1; }

function description()
{
    cat <<EOF
--help,-h; show this help and exit
--verbose,-v; show more information
--config=<config>; sensor config
--config-sample; show config sample and exit
--period=<sec>; logging period
EOF
}

function usage()
{
    cat <<EOF

log a basler sensor

usage: $scriptname [<options>]

options:
EOF
    description | sed 's/^/    /g' >&2
    cat <<EOF >&2

<config> is the file:path to the specific sensor config.

This command uses the log filter to directly log to a file without using stdout.
For high data throughput this is more efficient.

EOF
    exit
}

function config_sample()
{
    cat <<EOF
{
    "basler-aca1300-75gm":
    {
        "address": "localhost",
        "port": 55100,
        "binary": "t,3ui,614400ub",
        "fields": "t",
        "image-size": "1280,480",
        "image-offset": "0,0",
        "image-type": "ub",

        "device":
        {
            "address": "169.254.166.97",
            "serial-number": "21991077"     // alternative to "address"
        },

        "gige":
        {
            "packet-size": "8192"
        }
    }
}
EOF
    exit
}

function say() { echo "$scriptname: $@" >&2; }
function verbose() { (( options_verbose )) && say "$@"; }
function die() { say "$@"; exit 1; }

(( $( comma_options_has "--bash-completion" $@ ) )) && { description | comma_options_to_bash_completion; exit 0; }
(( $( comma_options_has "--help" $@ ) || $( comma_options_has "-h" $@ ) )) && usage
(( $( comma_options_has "--config-sample" $@ ) )) && config_sample

options="$( description | comma-options-to-name-value "$@" )"
comma_path_value_to_var --prefix=options < <( echo "$options" | grep '=' )

function load_config()
{
    local file path
    IFS=: read file path <<< "$1"

    cat "$file" | name-value-convert \
        | if [[ "$path" ]]; then sed "/^$path\//s#^$path/##"; else cat; fi
}

verbose "loading sensor config $options_config"

comma_path_value_to_var --prefix=config < <( load_config $options_config )

IFS=, read height width <<< $config_image_size
IFS=, read offset_x offset_y <<< $config_image_offset

args=
[[ $config_device_address ]] && args+=" --address $config_device_address"
[[ $config_device_serial_number ]] && args+=" --serial-number $config_device_serial_number"
[[ $height ]] && args+=" --height=$height"
[[ $width ]] && args+=" --width=$width"
[[ $offset_x ]] && args+=" --offset-x=$offset_x"
[[ $offset_y ]] && args+=" --offset-y=$offset_y"
[[ $config_image_type ]] && args+=" --image-type $config_image_type"
[[ $config_gige_packet_size ]] && args+=" --packet-size=$config_gige_packet_size"
[[ $options_verbose ]] && args+=" --verbose"
args=${args# }

command="basler-cat log=.,period:$options_period;null $args"

verbose "executing \"$command\""

while : ; do
    $command
    say "restarting ${command%% *}"
done
