#!/bin/bash

name=$( basename "$0" )

source $( which comma-application-util ) || { echo "$name: cannot source 'comma-application-util'" >&2; exit 1; }
source $( which comma-name-value-util ) || { echo "$name: cannot source 'comma-name-value-util'" >&2; exit 1; }

comma_path_value_to_var --prefix=input --export

[[ -r "$input_bag" ]] || { echo "$name: cannot read input bag file '$input_bag'" >&2; exit 1; }

output_fields_plain=$( ros-to-csv "$input_topic" --bag "$input_bag" --output-fields )
output_fields_indexed=$( ros-to-csv "$input_topic" --bag "$input_bag" --output-fields --index-output-fields )

echo "output/fields/plain=\"$output_fields_plain\""
echo "output/fields/indexed=\"$output_fields_indexed\""

ros-to-csv "$input_topic" --bag "$input_bag" \
    | if [[ -n "$input_output_lines" ]] ; then head -n $input_output_lines ; else cat ; fi \
    | name-value-from-csv "$output_fields_indexed" --output-line-number \
    | csv-quote --fields ,x --delimiter = \
    | sed 's/^/output\/line/'
