#!/bin/bash

source ../../input-to-raw

fields=$( ouster-to-csv lidar --output-fields )
format=$( ouster-to-csv lidar --output-format )

angle_fields=$( echo $fields | csv-fields clear --except bearing,elevation )

input_to_raw \
    | ouster-to-csv lidar --config ../../config.json \
    | csv-units --fields $angle_fields --binary $format --from radians --to degrees \
    | csv-from-bin $format \
    | name-value-from-csv --fields $fields --prefix output --line-number \
    | csv-quote --unquote --delimiter='='
