#!/bin/bash

function clean
{
    pkill -P $$
    return 0
}
function bye { clean; exit 1; }
trap bye INT TERM HUP
trap clean EXIT

omni_fields="speed,feedback/t,feedback/yaw,wayline/heading,error/cross_track,error/heading"
read -d '' omni_input <<END
10.0,20010101T000000.000000,0.11,0.1,0.0,0.01
11.0,20010101T000000.100000,0.09,0.1,0.0,-0.01
12.0,20010101T000000.200000,0.1,0.1,0.01,0
13.0,20010101T000000.300000,0.1,0.1,-0.01,0
14.0,20010101T000000.400000,0.11,0.1,0.01,0.01
15.0,20010101T000000.500000,0.09,0.1,-0.01,-0.01
16.0,20010101T000000.600000,0.0,0.1,0.01,-0.1
17.0,20010101T000000.700000,0.2,0.1,-0.01,0.1
END
omni_output=( $( echo -e "$omni_input" | control-command --fields=$omni_fields --cross-track-pid=1.11111,0,0 --heading-pid=0.12345,0,0 --steering=omni ) )

function echo_omni_result
{
    local lhs=$1
    local result=$2
    local speed time yaw wayline_heading cross_track_error heading_error turn_rate local_heading
    IFS=, read speed time yaw wayline_heading cross_track_error heading_error turn_rate local_heading <<< $result
    echo "$lhs/time=\"$time\""
    echo "$lhs/speed=$speed"
    echo "$lhs/wayline_heading=$wayline_heading"
    echo "$lhs/yaw=$yaw"
    echo "$lhs/cross_track_error=$cross_track_error"
    echo "$lhs/heading_error=$heading_error"
    echo "$lhs/turn_rate=$turn_rate"
    echo "$lhs/local_heading=$local_heading"
}

for(( i=0; i < ${#omni_output[@]}; i++ )); do echo_omni_result "omni/output[$i]" ${omni_output[i]}; done

clean
