#!/bin/bash

source $( type -p comma-application-util ) || { echo "cannot source 'comma-application-util'" >&2; exit 1; }

comma_path_value_to_var

echo -e "$input" | csv-to-bin 3ub | math-k-means --binary 3ub $options | csv-from-bin 3ub,ui,3d | name-value-from-csv point --prefix output -n -d @
comma_status_ok && echo 'result="success"' || echo 'result="failed"'
