#!/bin/bash

source $( type -p comma-application-util )

read params
fields="line_number,$( image-pinhole $params --input-fields )"
output_fields="$( image-pinhole $params --output-fields | csv-fields prefix --path output )"
csv-paste line-number - | image-pinhole $params --fields $fields > output/out
comma_status_ok || { echo "image-pinhole exited non-zero status: $result"; exit 1; }
cat output/out \
    | csv-shuffle --fields="$fields,$output_fields" \
                  --output-fields="line_number,$output_fields" \
    | name-value-from-csv --prefix=out --line-number \
                          --fields="line_number,$( echo $output_fields | csv-fields strip --path output )" \
    | csv-quote --unquote --delimiter='='
echo "count=$( cat output/out | wc -l )"
