#!/bin/bash

# Strip leading and trailing white-space, comments and blank lines
cmd_args=$( sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' )

output_dir=output

[[ -d $output_dir ]] || mkdir $output_dir
cd $output_dir

cmd_args=../$cmd_args           # first arg is necessarily the path to the data file

csv-from-mat $cmd_args \
    | if [[ $cmd_args =~ --binary ]]; then csv-from-bin $( csv-from-mat $cmd_args --output-format ); else cat; fi \
    | if [[ $cmd_args =~ -- ]]; then
          name-value-from-csv -f line -d : -n -p output
      else
          name-value-convert --no-brackets
      fi
