#!/usr/bin/python

import sys
import argparse
import json
import numpy
import scipy.io

description="""
convert from json to matlab .mat file
"""

epilog="""
examples:
  cat data.json | {script_name} file.mat
  
""".format( script_name=sys.argv[0].split('/')[-1] )

parser=argparse.ArgumentParser(description=description,epilog=epilog)
parser.add_argument("file",help="Matlab file name")

args=parser.parse_args()

def convert(input):
    if isinstance(input, dict):
        return {convert(key): convert(value) for key, value in input.iteritems()}
    elif isinstance(input, list):
        ls=[convert(element) for element in input]
        if len(input)>1 and isinstance(input[0],dict):
            dt=numpy.dtype([(k.encode('utf-8'),'O') for k in input[0].keys()])
            #build ndarray with type input[0] keys
            nar=numpy.ndarray(shape=(1,len(input)),dtype=dt)
            ix=0
            while ix<len(input):
                nar[0,ix]=tuple(convert(input[ix].values()))
                ix+=1
            return nar
        return ls
    elif isinstance(input, unicode):
        return input.encode('utf-8')
    elif isinstance(input,int):
        return float(input)
    else:
        return input

mat_data=json.load(sys.stdin)
mat_data=convert(mat_data)
scipy.io.savemat(args.file,mat_data)
