#!/bin/bash

source $( type -p comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }

read cv_depth
read mask_values

cv_depth=${cv_depth:-f} # Default to type f

function get_mask()
{
    echo "$mask_values" | csv-to-bin 6f | 
    cv-cat --input "no-header;rows=2;cols=1;type=3f" --output "no-header=0"
}

mask_file=mask.bin
[[ -d output ]] && mask_file=output/mask.bin

get_mask >$mask_file

csv-to-bin 6$cv_depth | 
    cv-cat --input "no-header;rows=2;cols=1;type=3$cv_depth" --output "no-header=0" | 
    cv-cat "multiply=load:$mask_file" | 
    csv-from-bin "t,3ui,6$cv_depth" |
    gawk '{ print "image[" NR "]=\"" $0 "\""  }'
