#!/bin/bash

name=$( basename $0 )
function replicate { printf "$1"; printf ",$1%.0s" $( seq -s' ' 2 $2 ); }

robot_mode_no_power=$( ur-arm-status --robot-mode-from-name no-power )
robot_mode_stop=$( ur-arm-status --robot-mode-from-name security-stopped )
robot_mode_init=$( ur-arm-status --robot-mode-from-name initialising )
joint_mode_idle=$( ur-arm-status --joint-mode-from-name idle )
joint_mode_init=$( ur-arm-status --joint-mode-from-name  initialisation )

config=./ur-arm.json
publisher_address="$( name-value-get --from json status/publisher/address < $config )"
publisher_port="$( name-value-get --from json status/publisher/port < $config )"
command_address="$( name-value-get --from json command/address < $config )"
command_port="$( name-value-get --from json command/port < $config )"
timeout="$( name-value-get --from json timeout < $config )"

function robot_mode { echo "$( nc $publisher_address $publisher_port | ur-arm-status --fields=mode | head -1 )"; }
function joint_modes { echo "$( nc $publisher_address $publisher_port | ur-arm-status --fields=joints/mode | head -1 )"; }

function wait_for_mode
{
    local expected_robot_mode="$1"
    local expected_joint_modes="$2"
    local -i timeout="$3"
    SECONDS=0
    while [[ "$( robot_mode )" != "$expected_robot_mode" || "$( joint_modes )" != "$expected_joint_modes" ]]; do
        sleep 0.1
        if (( SECONDS > timeout )); then echo "$name: timed out after waiting for $timeout seconds for robot mode $expected_robot_mode and joint modes $expected_joint_modes" >&2; exit 1; fi
    done
}

mode="$( robot_mode )"
if [[ -z "$mode" ]]; then echo "$name: failed to get mode, check if status daemon is publishing on port $publisher_port" >&2; exit 1; fi
if [[ "$mode" != "$robot_mode_no_power" ]]; then echo "$name: expected the arm to be in mode $robot_mode_no_power (no-power), got mode $mode" >&2; exit 1; fi

number_of_joints=$( joint_modes | tr ',' '\n' | wc -l )

echo "$name: turning the arm on at $( date +%X.%N ) ..."
echo "power on" | nc "$command_address" "$command_port"
wait_for_mode "$robot_mode_init" "$joint_modes_idle" "$timeout"
echo "stopj([$( replicate 0 $number_of_joints)])" | nc "$command_address" "$command_port"
wait_for_mode "$robot_mode_stop" "$( replicate $joint_mode_idle $number_of_joints)" "$timeout" 
echo "set robotmode run" | nc "$command_address" "$command_port"
wait_for_mode "$robot_mode_init" "$( replicate $joint_mode_init $number_of_joints )" "$timeout"
echo "$name: the arm is on and ready for initialisation at $( date +%X.%N )"

