#!/bin/bash

config=./ur-arm.json
address="$( name-value-get --from json status/address < $config )"
port="$( name-value-get --from json status/port < $config )"
publisher_port="$( name-value-get --from json status/publisher/port < $config )"

packet_size=$( ur-arm-status --packet-size )
socat -T 1 -u tcp:"$address":"$port" - | io-publish -s "$packet_size" tcp:"$publisher_port"
