#!/bin/bash
dir=$1
echo "ipx-generate-ld-conf: generating $( pwd )/ipx.conf..." >&2
echo "ipx-generate-ld-conf: ipx libs dir: $1" >&2
echo "$1" > ipx.conf
echo "ipx-generate-ld-conf: generated $( pwd )/ipx.conf" >&2
