#!/bin/bash

name=$( basename "$0" )

source $( which comma-application-util ) || { echo "$name: cannot source 'comma-application-util'" >&2; exit 1; }
source $( which comma-name-value-util ) || { echo "$name: cannot source 'comma-name-value-util'" >&2; exit 1; }

comma_path_value_to_var --prefix=input --export

[[ -r "$input_csv" ]] || { echo "$name: cannot read input csv file '$input_csv'" >&2; exit 1; }

cat "$input_csv" \
    | $input_head \
    | $input_converter \
    | ros-from-csv "$input_topic" --type "$input_type" --output-fields \
    | sed 's/^/fields="/;s/$/"/'
comma_status_ok
