#!/bin/bash

function options_description
{
    cat <<EOF
--config=[<config>]; config file name
--config-sample,--sample-config; output sample config
--config-fields; print list of config fields and exit
--input-fields; show waypoint fields (config is used if provided)
--output-fields; show output fields (config is used if provided)
--output-format; show output format of binary stream (config is used if provided)
--steering=[<steering>]; steering type (omni or skid)
EOF
}

function usage
{
    cat <<END

    take waypoints on stdin and output wheel commands based on the position feedback to stdout

options:
$( options_description | sed 's/^/    /g' )

notes:
    - command line options take precedence over config
    - output is binary if both waypoints and feedback are binary

examples:
    cat waypoints.csv | $scriptname --config=config.json > commands.csv
    $scriptname --input-fields --steering=omni
    $scriptname --output-fields --steering=omni
    $scriptname --output-format --steering=omni
    $scriptname --config-sample

END
    if (( ! $verbose )); then echo "for more output: $scriptname -h -v" >&2; return; fi
    cat <<END
example config file:
    
$( sample_config | sed 's/^/    /' )

    mode: waypoint following mode, fixed or dynamic
          fixed: wait until the current waypoint reached, then go to the next waypoint
          dynamic: if a new waypoint received, while the current waypoint is not reached, go to the new waypoint straightaway
    steering: steering type, omni or skid
              omni: wheels can rotate with respect to the body
              skid: wheels are fixed with respect to the body
    proximity: distance for deciding when a waypoint is reached
    past_endpoint: 1 -> besides proximity condition, consider a waypoint as reached if the vehicle has moved past the end line, 0 -> use only proximity condition
        ( the end line is a line which goes through the target waypoint and is perpendicular to the current wayline)
    heading/is_absolute_default: 1 -> interpret heading as the desired global (absolute) heading, 0 -> heading is relative offset wrt the wayline heading
        ( this describes default behaviour when is_absolute is not provided in the input; when is_absolute is given, it takes precedence )
    frequency: control frequency, i.e. the rate at which wheel commands are output when moving towards a waypoint
        ( when the last given waypoint is reached, no output is produced until new waypoints are given )
    reset: 1 -> reset pid integral upon reaching every target waypoint, 0 -> no reset
    pid:
        cross_track: p,i,d[,threshold] values, with optional integral threshold, for cross-track
        heading: the same for heading
    waypoints:
        fields: csv fields of waypoints (required fields: $default_waypoints_fields_skid for skid steering and $default_waypoints_fields_omni for omni steering)
        binary: binary format of waypoints (ascii stream is assumed by default)
    feedback:
        address: generic address for feedback
        fields: csv fields of feedback (required fields: $default_feedback_fields)
        binary: binary format of feedback (ascii stream is assumed by default)
        init_timeout: initial timeout waiting for feedback stream, passed to control-error

END
}

function sample_config
{
cat <<END
{
    "mode": "fixed",
    "steering": "omni",
    "proximity": "0.15",
    "past_endpoint": 1,
    "heading_is_absolute_default": 0,
    "heading_reached_threshold": "0.05",
    "frequency": "20.0",
    "reset": 0,
    "waypoints":
    {
        "fields": "x,y,heading,is_absolute,speed,id",
        "binary": "3d,b,d,ui"
    },
    "feedback":
    {
        "address": "tcp:localhost:12345",
        "fields": "t,x,y,yaw",
        "binary": "t,3d"
    },
    "pid":
    {
        "cross_track": "0.3,0,0",
        "heading": "0.5,0,0"
    }
}
END
}

function config_fields_mandatory
{
    cat <<END
mode
steering
proximity
past_endpoint
frequency
reset
feedback/address
pid/cross_track
pid/heading
END
}

function config_fields()
{
    cat <<EOF
frequency
heading/is_absolute_default
heading/reached_threshold
feedback/address
feedback/fields
feedback/binary
feedback/init_timeout
feedback/timeout
mode
past_endpoint
pid/cross_track
pid/heading
proximity
reset
steering
waypoints/fields
waypoints/binary
EOF
}

function is_binary
{
    [[ -z "$config_waypoints_binary" && -z "$config_feedback_binary" ]] && return 1
    [[ -n "$config_waypoints_binary" && -n "$config_feedback_binary" ]] && return 0
    die "input and feedback streams should be both ascii or both binary"
}

function die { echo "$scriptname: $1" >&2; exit 1; }

function prefix { csv-fields prefix --path $1; }

function set_default_waypoints_fields
{
    local steering=$1
    case "$steering" in
        omni) config_waypoints_fields=$waypoints_fields_omni ;;
        skid) config_waypoints_fields=$waypoints_fields_skid ;;
        *) die "steering '$steering' is not recongnised" ;;
    esac
}


scriptname=$( basename $0 )
source $( which comma-application-util ) || { echo "$scriptname: failed to source comma-application-util" >&2; exit 1; }

# default fields (note that default fields for waypoints depend on steering type and need to be set once the steering type is known)
config_feedback_fields="t,x,y,yaw"
waypoints_fields_omni="x,y,heading"
waypoints_fields_skid="x,y"

config_feedback_binary=""
config_waypoints_binary=""

feedback_format="t,d,d,d"

if (( $( comma_options_has --help "$@" ) || $( comma_options_has -h "$@" ) )); then
    (( $( comma_options_has --verbose "$@" ) || $( comma_options_has -v "$@" ) )) && verbose=1 || verbose=0
    usage $verbose
    exit
fi

if (( $( comma_options_has --sample-config "$@" ) || $( comma_options_has --config-sample "$@" ) )); then sample_config; exit; fi
if (( $( comma_options_has --config-fields "$@" ) )); then config_fields; exit; fi

eval $( options_description | grep '^--config=' | comma-options-to-name-value "$@" | comma_path_value_mangle )
if [[ -n "$config" ]]; then
    eval $( name-value-convert --from=json < "$config" | comma_path_value_mangle | sed 's#^#config_#' ; comma_status_ok ) || die "failed to import config '$config'"
fi
eval $( options_description | comma-options-to-name-value "$@" | comma_path_value_mangle )
[[ -z $config_steering ]] || steering="$config_steering"
if [[ -z "$config_waypoints_fields" ]]; then
    [[ "$steering" ]] || die "failed to set default waypoints/fields; steering type is required"
    set_default_waypoints_fields $steering
fi
[[ -z $config_heading_reached_threshold ]] || heading_reached_threshold="--heading-reached-threshold=$config_heading_reached_threshold"
if (( $( comma_options_has --input-fields "$@" ) )); then echo $config_waypoints_fields; exit; fi

error_fields=$( control-error --output-fields --status )
error_binary=$( control-error --output-format --status )

command_fields=$( control-command --steering=$steering --output-fields )
command_binary=$( control-command --steering=$steering --output-format )

if (( $( comma_options_has --output-fields "$@" ) )); then
    echo $( prefix feedback <<< $config_feedback_fields ),$error_fields,$( prefix command <<< $command_fields )
    exit
fi
if (( $( comma_options_has --output-format "$@" ) )); then
    echo ${config_feedback_binary:-$feedback_format},$error_binary,$command_binary
    exit
fi

passed_fields=$( prefix target <<< $config_waypoints_fields ),$( prefix feedback <<< $config_feedback_fields ),$error_fields
is_binary && passed_binary=$config_waypoints_binary,$config_feedback_binary,$error_binary || passed_binary=
[[ -z $config_feedback_timeout ]] || feedback_timeout="--feedback-timeout=$config_feedback_timeout"
[[ -n $config_feedback_init_timeout ]] || config_feedback_init_timeout="1"

config_fields_mandatory | sed 's/^/config_/g' | comma_path_assert_defined || die "found undefined config parameters"

grep -E '(^|,)is_absolute(,|$)' <<< $config_waypoints_fields &>/dev/null;
(( 0 == $? )) && has_absolute_field=1 || has_absolute_field=0
epsilon=0.0001

echo "$scriptname: starting control pipeline" >&2

if [[ 'skid' = $steering ]]
then
    if (( has_absolute_field ))
    then
        csv-eval --fields=$config_waypoints_fields --exit-if "( 1 == is_absolute ) & ( $epsilon < abs( speed ) )" --with-error "heading must not be absolute for skid steering (except spot turn)."
    elif (( config_heading_is_absolute_default ))
    then
        die "heading must not default to absolute for skid steering, check config file."
    else
        cat -
    fi
else
    cat -
fi |
control-error \
        --fields=$config_waypoints_fields \
        --binary=$config_waypoints_binary \
        "$config_feedback_address;fields=$config_feedback_fields;binary=$config_feedback_binary" --feedback-init-timeout $config_feedback_init_timeout \
        --mode=$config_mode \
        --proximity=$config_proximity \
        --frequency=$config_frequency \
        $( (( config_past_endpoint )) && echo --past-endpoint ) \
        $( (( config_heading_is_absolute_default )) && echo --heading-is-absolute ) \
        $heading_reached_threshold \
        --status \
        --flush \
        --verbose |
control-command \
        --fields=$passed_fields \
        --binary=$passed_binary \
        $feedback_timeout \
        --cross-track-pid=$config_pid_cross_track \
        --heading-pid=$config_pid_heading \
        --steering=$steering \
         $( (( config_reset )) && echo --reset ) \
        --flush \
        --verbose
comma_status_ok && status=0 || status=1
echo "$scriptname: control pipeline has ended with status=$status" >&2
exit $status
